// Code generated by entc, DO NOT EDIT.

package moviesource

const (
	// Label holds the string label denoting the moviesource type in the database.
	Label = "movie_source"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldMangaSerieSearchURL holds the string denoting the manga_serie_search_url field in the database.
	FieldMangaSerieSearchURL = "manga_serie_search_url"
	// FieldMangaFilmSearchURL holds the string denoting the manga_film_search_url field in the database.
	FieldMangaFilmSearchURL = "manga_film_search_url"
	// FieldSerieSearchURL holds the string denoting the serie_search_url field in the database.
	FieldSerieSearchURL = "serie_search_url"
	// FieldFilmSearchURL holds the string denoting the film_search_url field in the database.
	FieldFilmSearchURL = "film_search_url"
	// FieldMangaSerieLatestURL holds the string denoting the manga_serie_latest_url field in the database.
	FieldMangaSerieLatestURL = "manga_serie_latest_url"
	// FieldMangaFilmLatestURL holds the string denoting the manga_film_latest_url field in the database.
	FieldMangaFilmLatestURL = "manga_film_latest_url"
	// FieldSerieLatestURL holds the string denoting the serie_latest_url field in the database.
	FieldSerieLatestURL = "serie_latest_url"
	// FieldFilmLatestURL holds the string denoting the film_latest_url field in the database.
	FieldFilmLatestURL = "film_latest_url"
	// FieldMangaSerieLatestPostSelector holds the string denoting the manga_serie_latest_post_selector field in the database.
	FieldMangaSerieLatestPostSelector = "manga_serie_latest_post_selector"
	// FieldMangaFilmLatestPostSelector holds the string denoting the manga_film_latest_post_selector field in the database.
	FieldMangaFilmLatestPostSelector = "manga_film_latest_post_selector"
	// FieldSerieLatestPostSelector holds the string denoting the serie_latest_post_selector field in the database.
	FieldSerieLatestPostSelector = "serie_latest_post_selector"
	// FieldFilmLatestPostSelector holds the string denoting the film_latest_post_selector field in the database.
	FieldFilmLatestPostSelector = "film_latest_post_selector"
	// FieldMangaSerieSearchPostSelector holds the string denoting the manga_serie_search_post_selector field in the database.
	FieldMangaSerieSearchPostSelector = "manga_serie_search_post_selector"
	// FieldMangaFilmSearchPostSelector holds the string denoting the manga_film_search_post_selector field in the database.
	FieldMangaFilmSearchPostSelector = "manga_film_search_post_selector"
	// FieldSerieSearchPostSelector holds the string denoting the serie_search_post_selector field in the database.
	FieldSerieSearchPostSelector = "serie_search_post_selector"
	// FieldFilmSearchPostSelector holds the string denoting the film_search_post_selector field in the database.
	FieldFilmSearchPostSelector = "film_search_post_selector"
	// FieldMangaSerieArticleSelector holds the string denoting the manga_serie_article_selector field in the database.
	FieldMangaSerieArticleSelector = "manga_serie_article_selector"
	// FieldMangaFilmArticleSelector holds the string denoting the manga_film_article_selector field in the database.
	FieldMangaFilmArticleSelector = "manga_film_article_selector"
	// FieldSerieArticleSelector holds the string denoting the serie_article_selector field in the database.
	FieldSerieArticleSelector = "serie_article_selector"
	// FieldFilmArticleSelector holds the string denoting the film_article_selector field in the database.
	FieldFilmArticleSelector = "film_article_selector"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldURL holds the string denoting the url field in the database.
	FieldURL = "url"
	// Table holds the table name of the moviesource in the database.
	Table = "movie_sources"
)

// Columns holds all SQL columns for moviesource fields.
var Columns = []string{
	FieldID,
	FieldMangaSerieSearchURL,
	FieldMangaFilmSearchURL,
	FieldSerieSearchURL,
	FieldFilmSearchURL,
	FieldMangaSerieLatestURL,
	FieldMangaFilmLatestURL,
	FieldSerieLatestURL,
	FieldFilmLatestURL,
	FieldMangaSerieLatestPostSelector,
	FieldMangaFilmLatestPostSelector,
	FieldSerieLatestPostSelector,
	FieldFilmLatestPostSelector,
	FieldMangaSerieSearchPostSelector,
	FieldMangaFilmSearchPostSelector,
	FieldSerieSearchPostSelector,
	FieldFilmSearchPostSelector,
	FieldMangaSerieArticleSelector,
	FieldMangaFilmArticleSelector,
	FieldSerieArticleSelector,
	FieldFilmArticleSelector,
	FieldStatus,
	FieldName,
	FieldURL,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus bool
)
