// Code generated by entc, DO NOT EDIT.

package entdata

import (
	"context"
	"fmt"
	"log"

	"yola/internal/entdata/migrate"

	"yola/internal/entdata/moviesource"
	"yola/internal/entdata/tv"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
)

// Client is the client that holds all ent builders.
type Client struct {
	config
	// Schema is the client for creating, migrating and dropping schema.
	Schema *migrate.Schema
	// MovieSource is the client for interacting with the MovieSource builders.
	MovieSource *MovieSourceClient
	// Tv is the client for interacting with the Tv builders.
	Tv *TvClient
}

// NewClient creates a new client configured with the given options.
func NewClient(opts ...Option) *Client {
	cfg := config{log: log.Println, hooks: &hooks{}}
	cfg.options(opts...)
	client := &Client{config: cfg}
	client.init()
	return client
}

func (c *Client) init() {
	c.Schema = migrate.NewSchema(c.driver)
	c.MovieSource = NewMovieSourceClient(c.config)
	c.Tv = NewTvClient(c.config)
}

// Open opens a database/sql.DB specified by the driver name and
// the data source name, and returns a new client attached to it.
// Optional parameters can be added for configuring the client.
func Open(driverName, dataSourceName string, options ...Option) (*Client, error) {
	switch driverName {
	case dialect.MySQL, dialect.Postgres, dialect.SQLite:
		drv, err := sql.Open(driverName, dataSourceName)
		if err != nil {
			return nil, err
		}
		return NewClient(append(options, Driver(drv))...), nil
	default:
		return nil, fmt.Errorf("unsupported driver: %q", driverName)
	}
}

// Tx returns a new transactional client. The provided context
// is used until the transaction is committed or rolled back.
func (c *Client) Tx(ctx context.Context) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("entdata: cannot start a transaction within a transaction")
	}
	tx, err := newTx(ctx, c.driver)
	if err != nil {
		return nil, fmt.Errorf("entdata: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = tx
	return &Tx{
		ctx:         ctx,
		config:      cfg,
		MovieSource: NewMovieSourceClient(cfg),
		Tv:          NewTvClient(cfg),
	}, nil
}

// BeginTx returns a transactional client with specified options.
func (c *Client) BeginTx(ctx context.Context, opts *sql.TxOptions) (*Tx, error) {
	if _, ok := c.driver.(*txDriver); ok {
		return nil, fmt.Errorf("ent: cannot start a transaction within a transaction")
	}
	tx, err := c.driver.(interface {
		BeginTx(context.Context, *sql.TxOptions) (dialect.Tx, error)
	}).BeginTx(ctx, opts)
	if err != nil {
		return nil, fmt.Errorf("ent: starting a transaction: %w", err)
	}
	cfg := c.config
	cfg.driver = &txDriver{tx: tx, drv: c.driver}
	return &Tx{
		ctx:         ctx,
		config:      cfg,
		MovieSource: NewMovieSourceClient(cfg),
		Tv:          NewTvClient(cfg),
	}, nil
}

// Debug returns a new debug-client. It's used to get verbose logging on specific operations.
//
//	client.Debug().
//		MovieSource.
//		Query().
//		Count(ctx)
//
func (c *Client) Debug() *Client {
	if c.debug {
		return c
	}
	cfg := c.config
	cfg.driver = dialect.Debug(c.driver, c.log)
	client := &Client{config: cfg}
	client.init()
	return client
}

// Close closes the database connection and prevents new queries from starting.
func (c *Client) Close() error {
	return c.driver.Close()
}

// Use adds the mutation hooks to all the entity clients.
// In order to add hooks to a specific client, call: `client.Node.Use(...)`.
func (c *Client) Use(hooks ...Hook) {
	c.MovieSource.Use(hooks...)
	c.Tv.Use(hooks...)
}

// MovieSourceClient is a client for the MovieSource schema.
type MovieSourceClient struct {
	config
}

// NewMovieSourceClient returns a client for the MovieSource from the given config.
func NewMovieSourceClient(c config) *MovieSourceClient {
	return &MovieSourceClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `moviesource.Hooks(f(g(h())))`.
func (c *MovieSourceClient) Use(hooks ...Hook) {
	c.hooks.MovieSource = append(c.hooks.MovieSource, hooks...)
}

// Create returns a create builder for MovieSource.
func (c *MovieSourceClient) Create() *MovieSourceCreate {
	mutation := newMovieSourceMutation(c.config, OpCreate)
	return &MovieSourceCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of MovieSource entities.
func (c *MovieSourceClient) CreateBulk(builders ...*MovieSourceCreate) *MovieSourceCreateBulk {
	return &MovieSourceCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for MovieSource.
func (c *MovieSourceClient) Update() *MovieSourceUpdate {
	mutation := newMovieSourceMutation(c.config, OpUpdate)
	return &MovieSourceUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *MovieSourceClient) UpdateOne(ms *MovieSource) *MovieSourceUpdateOne {
	mutation := newMovieSourceMutation(c.config, OpUpdateOne, withMovieSource(ms))
	return &MovieSourceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *MovieSourceClient) UpdateOneID(id int) *MovieSourceUpdateOne {
	mutation := newMovieSourceMutation(c.config, OpUpdateOne, withMovieSourceID(id))
	return &MovieSourceUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for MovieSource.
func (c *MovieSourceClient) Delete() *MovieSourceDelete {
	mutation := newMovieSourceMutation(c.config, OpDelete)
	return &MovieSourceDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *MovieSourceClient) DeleteOne(ms *MovieSource) *MovieSourceDeleteOne {
	return c.DeleteOneID(ms.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *MovieSourceClient) DeleteOneID(id int) *MovieSourceDeleteOne {
	builder := c.Delete().Where(moviesource.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &MovieSourceDeleteOne{builder}
}

// Query returns a query builder for MovieSource.
func (c *MovieSourceClient) Query() *MovieSourceQuery {
	return &MovieSourceQuery{
		config: c.config,
	}
}

// Get returns a MovieSource entity by its id.
func (c *MovieSourceClient) Get(ctx context.Context, id int) (*MovieSource, error) {
	return c.Query().Where(moviesource.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *MovieSourceClient) GetX(ctx context.Context, id int) *MovieSource {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *MovieSourceClient) Hooks() []Hook {
	return c.hooks.MovieSource
}

// TvClient is a client for the Tv schema.
type TvClient struct {
	config
}

// NewTvClient returns a client for the Tv from the given config.
func NewTvClient(c config) *TvClient {
	return &TvClient{config: c}
}

// Use adds a list of mutation hooks to the hooks stack.
// A call to `Use(f, g, h)` equals to `tv.Hooks(f(g(h())))`.
func (c *TvClient) Use(hooks ...Hook) {
	c.hooks.Tv = append(c.hooks.Tv, hooks...)
}

// Create returns a create builder for Tv.
func (c *TvClient) Create() *TvCreate {
	mutation := newTvMutation(c.config, OpCreate)
	return &TvCreate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// CreateBulk returns a builder for creating a bulk of Tv entities.
func (c *TvClient) CreateBulk(builders ...*TvCreate) *TvCreateBulk {
	return &TvCreateBulk{config: c.config, builders: builders}
}

// Update returns an update builder for Tv.
func (c *TvClient) Update() *TvUpdate {
	mutation := newTvMutation(c.config, OpUpdate)
	return &TvUpdate{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOne returns an update builder for the given entity.
func (c *TvClient) UpdateOne(t *Tv) *TvUpdateOne {
	mutation := newTvMutation(c.config, OpUpdateOne, withTv(t))
	return &TvUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// UpdateOneID returns an update builder for the given id.
func (c *TvClient) UpdateOneID(id int) *TvUpdateOne {
	mutation := newTvMutation(c.config, OpUpdateOne, withTvID(id))
	return &TvUpdateOne{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// Delete returns a delete builder for Tv.
func (c *TvClient) Delete() *TvDelete {
	mutation := newTvMutation(c.config, OpDelete)
	return &TvDelete{config: c.config, hooks: c.Hooks(), mutation: mutation}
}

// DeleteOne returns a delete builder for the given entity.
func (c *TvClient) DeleteOne(t *Tv) *TvDeleteOne {
	return c.DeleteOneID(t.ID)
}

// DeleteOneID returns a delete builder for the given id.
func (c *TvClient) DeleteOneID(id int) *TvDeleteOne {
	builder := c.Delete().Where(tv.ID(id))
	builder.mutation.id = &id
	builder.mutation.op = OpDeleteOne
	return &TvDeleteOne{builder}
}

// Query returns a query builder for Tv.
func (c *TvClient) Query() *TvQuery {
	return &TvQuery{
		config: c.config,
	}
}

// Get returns a Tv entity by its id.
func (c *TvClient) Get(ctx context.Context, id int) (*Tv, error) {
	return c.Query().Where(tv.ID(id)).Only(ctx)
}

// GetX is like Get, but panics if an error occurs.
func (c *TvClient) GetX(ctx context.Context, id int) *Tv {
	obj, err := c.Get(ctx, id)
	if err != nil {
		panic(err)
	}
	return obj
}

// Hooks returns the client hooks.
func (c *TvClient) Hooks() []Hook {
	return c.hooks.Tv
}
