// Code generated by entc, DO NOT EDIT.

package entdata

import (
	"context"
	"fmt"
	"math"
	"yola/internal/entdata/moviesource"
	"yola/internal/entdata/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MovieSourceQuery is the builder for querying MovieSource entities.
type MovieSourceQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.MovieSource
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the MovieSourceQuery builder.
func (msq *MovieSourceQuery) Where(ps ...predicate.MovieSource) *MovieSourceQuery {
	msq.predicates = append(msq.predicates, ps...)
	return msq
}

// Limit adds a limit step to the query.
func (msq *MovieSourceQuery) Limit(limit int) *MovieSourceQuery {
	msq.limit = &limit
	return msq
}

// Offset adds an offset step to the query.
func (msq *MovieSourceQuery) Offset(offset int) *MovieSourceQuery {
	msq.offset = &offset
	return msq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (msq *MovieSourceQuery) Unique(unique bool) *MovieSourceQuery {
	msq.unique = &unique
	return msq
}

// Order adds an order step to the query.
func (msq *MovieSourceQuery) Order(o ...OrderFunc) *MovieSourceQuery {
	msq.order = append(msq.order, o...)
	return msq
}

// First returns the first MovieSource entity from the query.
// Returns a *NotFoundError when no MovieSource was found.
func (msq *MovieSourceQuery) First(ctx context.Context) (*MovieSource, error) {
	nodes, err := msq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{moviesource.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (msq *MovieSourceQuery) FirstX(ctx context.Context) *MovieSource {
	node, err := msq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first MovieSource ID from the query.
// Returns a *NotFoundError when no MovieSource ID was found.
func (msq *MovieSourceQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = msq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{moviesource.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (msq *MovieSourceQuery) FirstIDX(ctx context.Context) int {
	id, err := msq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single MovieSource entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one MovieSource entity is found.
// Returns a *NotFoundError when no MovieSource entities are found.
func (msq *MovieSourceQuery) Only(ctx context.Context) (*MovieSource, error) {
	nodes, err := msq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{moviesource.Label}
	default:
		return nil, &NotSingularError{moviesource.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (msq *MovieSourceQuery) OnlyX(ctx context.Context) *MovieSource {
	node, err := msq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only MovieSource ID in the query.
// Returns a *NotSingularError when more than one MovieSource ID is found.
// Returns a *NotFoundError when no entities are found.
func (msq *MovieSourceQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = msq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{moviesource.Label}
	default:
		err = &NotSingularError{moviesource.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (msq *MovieSourceQuery) OnlyIDX(ctx context.Context) int {
	id, err := msq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of MovieSources.
func (msq *MovieSourceQuery) All(ctx context.Context) ([]*MovieSource, error) {
	if err := msq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return msq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (msq *MovieSourceQuery) AllX(ctx context.Context) []*MovieSource {
	nodes, err := msq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of MovieSource IDs.
func (msq *MovieSourceQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := msq.Select(moviesource.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (msq *MovieSourceQuery) IDsX(ctx context.Context) []int {
	ids, err := msq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (msq *MovieSourceQuery) Count(ctx context.Context) (int, error) {
	if err := msq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return msq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (msq *MovieSourceQuery) CountX(ctx context.Context) int {
	count, err := msq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (msq *MovieSourceQuery) Exist(ctx context.Context) (bool, error) {
	if err := msq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return msq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (msq *MovieSourceQuery) ExistX(ctx context.Context) bool {
	exist, err := msq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the MovieSourceQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (msq *MovieSourceQuery) Clone() *MovieSourceQuery {
	if msq == nil {
		return nil
	}
	return &MovieSourceQuery{
		config:     msq.config,
		limit:      msq.limit,
		offset:     msq.offset,
		order:      append([]OrderFunc{}, msq.order...),
		predicates: append([]predicate.MovieSource{}, msq.predicates...),
		// clone intermediate query.
		sql:    msq.sql.Clone(),
		path:   msq.path,
		unique: msq.unique,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		MangaSerieSearchURL string `json:"manga_serie_search_url,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.MovieSource.Query().
//		GroupBy(moviesource.FieldMangaSerieSearchURL).
//		Aggregate(entdata.Count()).
//		Scan(ctx, &v)
//
func (msq *MovieSourceQuery) GroupBy(field string, fields ...string) *MovieSourceGroupBy {
	grbuild := &MovieSourceGroupBy{config: msq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := msq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return msq.sqlQuery(ctx), nil
	}
	grbuild.label = moviesource.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		MangaSerieSearchURL string `json:"manga_serie_search_url,omitempty"`
//	}
//
//	client.MovieSource.Query().
//		Select(moviesource.FieldMangaSerieSearchURL).
//		Scan(ctx, &v)
//
func (msq *MovieSourceQuery) Select(fields ...string) *MovieSourceSelect {
	msq.fields = append(msq.fields, fields...)
	selbuild := &MovieSourceSelect{MovieSourceQuery: msq}
	selbuild.label = moviesource.Label
	selbuild.flds, selbuild.scan = &msq.fields, selbuild.Scan
	return selbuild
}

func (msq *MovieSourceQuery) prepareQuery(ctx context.Context) error {
	for _, f := range msq.fields {
		if !moviesource.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("entdata: invalid field %q for query", f)}
		}
	}
	if msq.path != nil {
		prev, err := msq.path(ctx)
		if err != nil {
			return err
		}
		msq.sql = prev
	}
	return nil
}

func (msq *MovieSourceQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*MovieSource, error) {
	var (
		nodes = []*MovieSource{}
		_spec = msq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		return (*MovieSource).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		node := &MovieSource{config: msq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, msq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (msq *MovieSourceQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := msq.querySpec()
	_spec.Node.Columns = msq.fields
	if len(msq.fields) > 0 {
		_spec.Unique = msq.unique != nil && *msq.unique
	}
	return sqlgraph.CountNodes(ctx, msq.driver, _spec)
}

func (msq *MovieSourceQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := msq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("entdata: check existence: %w", err)
	}
	return n > 0, nil
}

func (msq *MovieSourceQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   moviesource.Table,
			Columns: moviesource.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: moviesource.FieldID,
			},
		},
		From:   msq.sql,
		Unique: true,
	}
	if unique := msq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := msq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, moviesource.FieldID)
		for i := range fields {
			if fields[i] != moviesource.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := msq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := msq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := msq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := msq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (msq *MovieSourceQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(msq.driver.Dialect())
	t1 := builder.Table(moviesource.Table)
	columns := msq.fields
	if len(columns) == 0 {
		columns = moviesource.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if msq.sql != nil {
		selector = msq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if msq.unique != nil && *msq.unique {
		selector.Distinct()
	}
	for _, p := range msq.predicates {
		p(selector)
	}
	for _, p := range msq.order {
		p(selector)
	}
	if offset := msq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := msq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// MovieSourceGroupBy is the group-by builder for MovieSource entities.
type MovieSourceGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (msgb *MovieSourceGroupBy) Aggregate(fns ...AggregateFunc) *MovieSourceGroupBy {
	msgb.fns = append(msgb.fns, fns...)
	return msgb
}

// Scan applies the group-by query and scans the result into the given value.
func (msgb *MovieSourceGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := msgb.path(ctx)
	if err != nil {
		return err
	}
	msgb.sql = query
	return msgb.sqlScan(ctx, v)
}

func (msgb *MovieSourceGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range msgb.fields {
		if !moviesource.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := msgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := msgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (msgb *MovieSourceGroupBy) sqlQuery() *sql.Selector {
	selector := msgb.sql.Select()
	aggregation := make([]string, 0, len(msgb.fns))
	for _, fn := range msgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(msgb.fields)+len(msgb.fns))
		for _, f := range msgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(msgb.fields...)...)
}

// MovieSourceSelect is the builder for selecting fields of MovieSource entities.
type MovieSourceSelect struct {
	*MovieSourceQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (mss *MovieSourceSelect) Scan(ctx context.Context, v interface{}) error {
	if err := mss.prepareQuery(ctx); err != nil {
		return err
	}
	mss.sql = mss.MovieSourceQuery.sqlQuery(ctx)
	return mss.sqlScan(ctx, v)
}

func (mss *MovieSourceSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := mss.sql.Query()
	if err := mss.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
