// Code generated by entc, DO NOT EDIT.

package entdata

import (
	"yola/internal/entdata/moviesource"
	"yola/internal/entdata/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	moviesourceFields := schema.MovieSource{}.Fields()
	_ = moviesourceFields
	// moviesourceDescStatus is the schema descriptor for status field.
	moviesourceDescStatus := moviesourceFields[20].Descriptor()
	// moviesource.DefaultStatus holds the default value on creation for the status field.
	moviesource.DefaultStatus = moviesourceDescStatus.Default.(bool)
}
