// Code generated by entc, DO NOT EDIT.

package tv

const (
	// Label holds the string label denoting the tv type in the database.
	Label = "tv"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldLogo holds the string denoting the logo field in the database.
	FieldLogo = "logo"
	// FieldVideo holds the string denoting the video field in the database.
	FieldVideo = "video"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldCountry holds the string denoting the country field in the database.
	FieldCountry = "country"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldLanguage holds the string denoting the language field in the database.
	FieldLanguage = "language"
	// Table holds the table name of the tv in the database.
	Table = "tvs"
)

// Columns holds all SQL columns for tv fields.
var Columns = []string{
	FieldID,
	FieldLogo,
	FieldVideo,
	FieldTitle,
	FieldStatus,
	FieldCountry,
	FieldDescription,
	FieldLanguage,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// LogoValidator is a validator for the "logo" field. It is called by the builders before save.
	LogoValidator func(string) error
	// VideoValidator is a validator for the "video" field. It is called by the builders before save.
	VideoValidator func(string) error
	// TitleValidator is a validator for the "title" field. It is called by the builders before save.
	TitleValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus bool
	// DefaultCountry holds the default value on creation for the "country" field.
	DefaultCountry string
	// DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	DescriptionValidator func(string) error
	// DefaultLanguage holds the default value on creation for the "language" field.
	DefaultLanguage string
)
