// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// MovieSourcesColumns holds the columns for the "movie_sources" table.
	MovieSourcesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "manga_serie_search_url", Type: field.TypeString, Nullable: true},
		{Name: "manga_film_search_url", Type: field.TypeString, Nullable: true},
		{Name: "serie_search_url", Type: field.TypeString, Nullable: true},
		{Name: "film_search_url", Type: field.TypeString, Nullable: true},
		{Name: "manga_serie_latest_url", Type: field.TypeString, Nullable: true},
		{Name: "manga_film_latest_url", Type: field.TypeString, Nullable: true},
		{Name: "serie_latest_url", Type: field.TypeString, Nullable: true},
		{Name: "film_latest_url", Type: field.TypeString, Nullable: true},
		{Name: "manga_serie_latest_post_selector", Type: field.TypeJSON, Nullable: true},
		{Name: "manga_film_latest_post_selector", Type: field.TypeJSON, Nullable: true},
		{Name: "serie_latest_post_selector", Type: field.TypeJSON, Nullable: true},
		{Name: "film_latest_post_selector", Type: field.TypeJSON, Nullable: true},
		{Name: "manga_serie_search_post_selector", Type: field.TypeJSON, Nullable: true},
		{Name: "manga_film_search_post_selector", Type: field.TypeJSON, Nullable: true},
		{Name: "serie_search_post_selector", Type: field.TypeJSON, Nullable: true},
		{Name: "film_search_post_selector", Type: field.TypeJSON, Nullable: true},
		{Name: "manga_serie_article_selector", Type: field.TypeJSON, Nullable: true},
		{Name: "manga_film_article_selector", Type: field.TypeJSON, Nullable: true},
		{Name: "serie_article_selector", Type: field.TypeJSON, Nullable: true},
		{Name: "film_article_selector", Type: field.TypeJSON, Nullable: true},
		{Name: "status", Type: field.TypeBool, Default: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "url", Type: field.TypeString},
	}
	// MovieSourcesTable holds the schema information for the "movie_sources" table.
	MovieSourcesTable = &schema.Table{
		Name:       "movie_sources",
		Columns:    MovieSourcesColumns,
		PrimaryKey: []*schema.Column{MovieSourcesColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		MovieSourcesTable,
	}
)

func init() {
}
