// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// MovieSource is the predicate function for moviesource builders.
type MovieSource func(*sql.Selector)
